behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 4096 #default was 2048
      buffer_size: 40960 #default was 20480
      learning_rate: 0.005 #default was 0.003
      beta: 0.004 #default is 0.004
      epsilon: 0.2 #default is 0.2
      lambd: 0.95
      num_epoch: 5 #default is 8
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512 #default is 1024
      num_layers: 10
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 1000
    summary_freq: 10000
    self_play:
      save_steps: 50000
      team_change: 100000
      swap_steps: 2000
      window: 5
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0